#!/bin/bash
# validint -- Проверяет целые числа, поддерживает отрицательные значения
validint()
{
   # Проверяет первое значение и сравнивает с минимальным значением $2 и/или
   #   с максимальным значением $3, если они заданы. Если проверяемое значение
   #   вне заданного диапазона или не является допустимым целым числом,
   #   возвращается признак ошибки.
   
   number="$1"; 
   min="$2"; 
   max="$3"

	if [ -z $number ] ; then
	echo "You didn't enter anything. Please enter a number." >&2
	return 1 
      fi

# Первый символ –- знак "минус"?
	if [ "${number%${number#?}}" = "-" ] ; then
     		testvalue="${number#?}" # Оставить для проверки все, кроме первого символа
   	else
     		testvalue="$number"
   	fi
   # Удалить все цифры из числа для проверки.
   nodigits="$(echo $testvalue | sed 's/[[:digit:]]//g')"
        # Проверить наличие нецифровых символов.
	if [ ! -z $nodigits ] ; 
           then
           echo "Invalid number format! Only digits, no commas, spaces, etc." >&2
	return 1 
	fi

	if [ ! -z $min ] ; 
           then
	# Входное значение меньше минимального? 
		if [ "$number" -lt "$min" ] ; 
		then
       		echo "Your value is too small: smallest acceptable value is $min." >&2
		return 1 
		fi
	fi
   if [ ! -z $max ] ; 
      then
     # Входное значение больше максимального?
     if [ "$number" -gt "$max" ] ; 
        then
        echo "Your value is too big: largest acceptable value is $max." >&2
	return 1 
	fi
   fi
return 0
}

## Проверка ввода
#    if validint "$1" "$2" "$3" ; then
#    echo "Input is a valid integer within your constraints."
#fi
